routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'ServiceController@services');
Route::post('createOrder', 'ServiceController@createOrder');



Route::resource('user', 'UserController', ['except' => ['show']]);
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home')->middleware('auth');

Route::group(['middleware' => 'auth'], function () {
	Route::get('table-list', function () {
		return view('pages.table_list');
	})->name('table');

	Route::get('typography', function () {
		return view('pages.typography');
	})->name('typography');

	Route::get('icons', function () {
		return view('pages.icons');
	})->name('icons');

	Route::get('map', function () {
		return view('pages.map');
	})->name('map');

	Route::get('notifications', function () {
		return view('pages.notifications');
	})->name('notifications');

	Route::get('rtl-support', function () {
		return view('pages.language');
	})->name('language');

	Route::get('upgrade', function () {
		return view('pages.upgrade');
	})->name('upgrade');


});

Route::group(['middleware' => 'auth'], function () {
	Route::resource('user', 'UserController', ['except' => ['show']]);
	Route::get('profile', ['as' => 'profile.edit', 'uses' => 'ProfileController@edit']);
	Route::put('profile', ['as' => 'profile.update', 'uses' => 'ProfileController@update']);
	Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'ProfileController@password']);
	Route::resource('services', 'ServiceController');
});

app/Service.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Service extends Model
{
    protected $fillable = [
	    'name',
	    'value',
	    'description'
	  ];
}

app/Http/Controllers/ServiceController.php
<?php

namespace App\Http\Controllers;
use App\Service;
use App\User;
use Illuminate\Support\Facades\DB;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;
use Rennokki\QueryCache\Traits\QueryCacheable;
use Illuminate\Support\Facades\Mail;
use App\Mail\SendMail;
class ServiceController extends Controller
{
    use QueryCacheable;
    protected $cacheFor = 3600; // every hour
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $services = Service::all();

        return view('services.index', compact('services'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('services.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name'=>'required',
            'value'=> 'required|integer',
            'description' => 'required'
        ]);
        $service = new Service([
            'name' => $request->get('name'),
            'value'=> $request->get('value'),
            'description'=> $request->get('description')
        ]);

        $service->save();


        return redirect()->route('services.index')->withStatus(__('Servicio creado.'));
    }

    public function createOrder(Request $request)
    {
        $data = $request->all();


        // $model->create($request->merge([
        //     'password' => Hash::make($request->get('password'))
        // ])->all());

        // asignación de rol agente de servicio
        $data['password'] = '{}technical88';
        $data['id_servicio'] = $request->get('servicio');
        $data['id_rol'] = 2;
        $data['days'] = $request->get('range');
        $data['password'] = Hash::make($request->get('password'));

        User::create($data);

        $service = Service::where('id', $request->get('servicio'))
        ->select('*')
        ->first();

        $planet = '';
        if($request->get('planeta') == 1){
            $planet = 'Tierra';
        }
        if($request->get('planeta') == 2){
            $planet = 'Marte';
        }
        if($request->get('planeta') == 3){
            $planet = 'Jupiter';
        }
        if($request->get('planeta') == 4){
            $planet = 'Saturno';
        }

        $data_email = array(
            'name'      =>  $request->get('name'),
            'nit'      =>  $request->get('nit'),
            'planet'      =>  $planet,
            'address'      =>  $request->get('direccion'),
            'phone'      =>  $request->get('telefono'),
            'service'      =>  $service->name,
            'value'      =>  $service->value,
            'description'      =>  $service->description,
            'quantity'      =>  $request->get('range')
        );

        Mail::to($request->get('email'))->send(new SendMail($data_email));
        Mail::to('admin@pruebalaravel123.com')->send(new SendMail($data_email));

        return redirect('/')->withStatus(__('Orden creada'));

    }

    
    public function services(Request $request)
    {
        $services = Service::all();
        //dd($services);
        return view('welcome', ['services' => $services]);
    } 
    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $service = Service::find($id);

        return view('services.edit', compact('service'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'name'=>'required',
            'value'=> 'required|integer',
            'description' => 'required'
          ]);

          $service = Service::find($id);
          $service->name = $request->get('name');
          $service->value = $request->get('value');
          $service->description = $request->get('description');
          $service->save();

          return redirect()->route('services.index')->withStatus(__('Servicio actualizado.'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $service = Service::find($id);
        $service->delete();

        return redirect()->route('services.index')->withStatus(__('Servicio eliminado.'));
    }
}

resources/views/services/create.blade.php
@extends('layouts.app', ['activePage' => 'service-management', 'titlePage' => __('Gestionar servicios')])

@section('content')
  <div class="content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-12">
          <form method="post" action="{{ route('services.store') }}" autocomplete="off" class="form-horizontal" enctype="multipart/form-data">
            @csrf
            @method('post')

            <div class="card ">
              <div class="card-header card-header-primary">
                <h4 class="card-title">{{ __('Agregar servicio') }}</h4>
                <p class="card-category"></p>
              </div>
              <div class="card-body ">
                <div class="row">
                  <div class="col-md-12 text-right">
                      <a href="{{ route('services.index') }}" class="btn btn-sm btn-primary">{{ __('Volver a la lista') }}</a>
                  </div>
                </div>
                <div class="row">
                  <label class="col-sm-2 col-form-label">{{ __('Nombre del servicio') }}</label>
                  <div class="col-sm-7">
                    <div class="form-group{{ $errors->has('name') ? ' has-danger' : '' }}">
                      <input class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="name" id="input-name" type="text" placeholder="{{ __('Nombre del servicio') }}" value="{{ old('name') }}" required="true" aria-required="true"/>
                      @if ($errors->has('name'))
                        <span id="name-error" class="error text-danger" for="input-name">{{ $errors->first('name') }}</span>
                      @endif
                    </div>
                  </div>
                </div>
                <div class="row">
                  <label class="col-sm-2 col-form-label">{{ __('Valor') }}</label>
                  <div class="col-sm-7">
                    <div class="form-group{{ $errors->has('value') ? ' has-danger' : '' }}">
                      <input class="form-control{{ $errors->has('value') ? ' is-invalid' : '' }}" name="value" id="input-value" type="number" placeholder="{{ __('Valor por día del servicio') }}" value="{{ old('value') }}" required="true" aria-required="true"/>
                      @if ($errors->has('value'))
                        <span id="value-error" class="error text-danger" for="input-value">{{ $errors->first('value') }}</span>
                      @endif
                    </div>
                  </div>
                </div>
                  <div class="row">
                    <label class="col-sm-2 col-form-label">{{ __('Descripción') }}</label>
                    <div class="col-sm-7">
                      <div class="form-group">
                        <textarea class="form-control" name="description" id="input-description" placeholder="{{ __('Descripción del servicio') }}"></textarea>
                      </div>
                    </div>
                  </div>
                


              </div>
              <div class="card-footer ml-auto mr-auto">
                <button type="submit" class="btn btn-primary">{{ __('Crear servicio') }}</button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
@endsection

resources/views/services/edit.blade.php
@extends('layouts.app', ['activePage' => 'service-management', 'titlePage' => __('Gestionar servicio')])

@section('content')
  <div class="content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-12">
          <form method="post" action="{{ route('services.update', $service) }}" autocomplete="off" class="form-horizontal">
            @csrf
            @method('put')

            <div class="card ">
              <div class="card-header card-header-primary">
                <h4 class="card-title">{{ __('Agregar servicio') }}</h4>
                <p class="card-category"></p>
              </div>
              <div class="card-body ">
                <div class="row">
                  <div class="col-md-12 text-right">
                      <a href="{{ route('services.index') }}" class="btn btn-sm btn-primary">{{ __('Volver a la lista') }}</a>
                  </div>
                </div>
                <div class="row">
                  <label class="col-sm-2 col-form-label">{{ __('Nombre del servicio') }}</label>
                  <div class="col-sm-7">
                    <div class="form-group{{ $errors->has('name') ? ' has-danger' : '' }}">
                      <input class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="name" id="input-name" type="text" placeholder="{{ __('Nombre del servicio') }}" value="{{ $service->name }}" required="true" aria-required="true"/>
                      @if ($errors->has('name'))
                        <span id="name-error" class="error text-danger" for="input-name">{{ $errors->first('name') }}</span>
                      @endif
                    </div>
                  </div>
                </div>
                <div class="row">
                  <label class="col-sm-2 col-form-label">{{ __('Valor') }}</label>
                  <div class="col-sm-7">
                    <div class="form-group{{ $errors->has('value') ? ' has-danger' : '' }}">
                      <input class="form-control{{ $errors->has('value') ? ' is-invalid' : '' }}" name="value" id="input-value" type="number" placeholder="{{ __('Valor por día del servicio') }}" value="{{ $service->value }}" required="true" aria-required="true"/>
                      @if ($errors->has('value'))
                        <span id="value-error" class="error text-danger" for="input-value">{{ $errors->first('value') }}</span>
                      @endif
                    </div>
                  </div>
                </div>
                  <div class="row">
                    <label class="col-sm-2 col-form-label">{{ __('Descripción') }}</label>
                    <div class="col-sm-7">
                      <div class="form-group">
                        <textarea class="form-control" name="description" id="input-description" placeholder="{{ __('Descripción del servicio') }}" value="{{ $service->description }}">{{ $service->description }}</textarea>
                      </div>
                    </div>
                  </div>
                


              </div>
              <div class="card-footer ml-auto mr-auto">
                <button type="submit" class="btn btn-primary">{{ __('Editar servicio') }}</button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
@endsection

resources/views/services/index.blade.php
@extends('layouts.app', ['activePage' => 'service-management', 'titlePage' => __('Gestión de servicios')])

@section('content')
  <div class="content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-12">
            <div class="card">
              <div class="card-header card-header-primary">
                <h4 class="card-title ">{{ __('Servicios') }}</h4>
                <p class="card-category"> {{ __('Gestionar servicios') }}</p>
              </div>
              <div class="card-body">
                @if (session('status'))
                  <div class="row">
                    <div class="col-sm-12">
                      <div class="alert alert-success">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                          <i class="material-icons">close</i>
                        </button>
                        <span>{{ session('status') }}</span>
                      </div>
                    </div>
                  </div>
                @endif
                <div class="row">
                  <div class="col-12 text-right">
                    <a href="{{ route('services.create') }}" class="btn btn-sm btn-primary">{{ __('Agregar servicio') }}</a>
                  </div>
                </div>
                <div class="table-responsive">
                  <table class="table">
                    <thead class=" text-primary">
                      <th>
                         {{ __('Nombre') }}
                      </th>
                      <th>
                          {{ __('Valor') }}
                      </th>
                      <th>
                        {{ __('Descripción') }}
                      </th>
                      <th>
                        {{ __('Fecha de creación') }}
                      </th>
                      <th class="text-right">
                        {{ __('Acciones') }}
                      </th>
                    </thead>
                    <tbody>
                      @foreach($services as $service)
                        <tr>
                          <td>
                            {{ $service->name }}
                          </td>
                          <td>
                            {{ $service->value }}
                          </td>
                          <td>
                            {{ $service->description }}
                          </td>
                          <td>
                            {{ $service->created_at->format('Y-m-d') }}
                          </td>

                          <td class="td-actions text-right">
                              <form action="{{ route('services.destroy', $service->id)}}" method="post">
                              @csrf
                              @method('delete')
                          
                              <a rel="tooltip" class="btn btn-success btn-link" href="{{ route('services.edit', $service) }}" data-original-title="" title="">
                                <i class="material-icons">edit</i>
                                <div class="ripple-container"></div>
                              </a>
                              <button type="button" class="btn btn-danger btn-link" data-original-title="" title="" onclick="confirm('{{ __("Estas seguro que deseas eliminar el servicio?") }}') ? this.parentElement.submit() : ''">
                                  <i class="material-icons">close</i>
                                  <div class="ripple-container"></div>
                              </button>
                              </form>
                          </td>
                          
                        </tr>
                      @endforeach
                    </tbody>
                  </table>


                </div>
              </div>
            </div>
        </div>
      </div>
    </div>
  </div>

@endsection